services:
  PaddleOCR:
    build: .
    container_name: paddle-ocr-server # 自定义容器名
    image: paddle-ocr-server:latest # 第2步自定义的镜像名与标签
    environment:
      - TZ=Asia/Shanghai
      - OCR_LANGUAGE=ch
    ports:
      - "8080:8000" # 自定义服务暴露端口, 8000为FastAPI默认端口, 不做修改,只能改前面的8000,不要忘了引号
    restart: unless-stopped
